### ISSUE TITLE
Error on MongoDB.Driver version 3

### ISSUE THREAD

**Issue by nataphat** [matteofabbri/AspNetCore.Identity.Mongo#134]
**Describe the bug**
I upgrade MongoDB.Driver version 2.30 to 3
AspNetCore.Identity.Mongo Error 

**Screenshots**
![Screenshot 2024-11-02 124338](https://github.com/user-attachments/assets/ae356058-ed9e-463e-b04b-bf31536d4390)

![image](https://github.com/user-attachments/assets/dd2141e6-b5ee-43d3-9ceb-a577627e9da3)

**Environment **
 - .Net Core version: 8
 - Package Version: 9.0

**Comment by twiggins-cordel** [comment]
Hello,

I would like to see support for the `MongoDB.Driver` version `3.0.0` too, but would be good to not be at the expense of backwards compatibility.

The `MongoDB.Driver.Core` is no longer being published since `MongoDB.Driver` version `3.0.0` as noted in the 3.0.0 breaking changes: https://www.mongodb.com/docs/drivers/csharp/current/upgrade/v3/#version-3.0-breaking-changes

I've come across this issue in a separate project where we removed references to the methods that were calling functions from that library, these were no longer needed in our case.

Also, to provide backwards compatibility I've seen other libraries provide multiple major versions that target different versions for the `MongoDB.Driver` which might need to be done here too?

Two example projects that are doing this:
* [AspNetCore.DataProtection.MongoDb](https://www.nuget.org/packages/AspNetCore.DataProtection.MongoDb#versions-body-tab) - version 8.0.0 targets MongoDB.Driver 3.0.0, and version 7.0.0 targets MongoDB.Driver 2.28.0
* [CSharp.Mongo.Migration](https://www.nuget.org/packages/CSharp.Mongo.Migration) - version 3.0.0 targets MongoDB.Driver 3.0.0, version 2.0.0 targets MongoDB.Driver 2.28.0

I believe this is related to the MongoDB.Driver introducing Strong-Named Assemblies in 2.27.0 causing these annoying mismatch versioning issues.

**Comment by vova3211** [comment]
hi there

packages v9.x.x depends on the `MongoDB.Driver` v2.28.0. I'm working on upgrading library, but need to verify all breaking changes. It should be done soon

regarding supporting multiple versions:
1. due to breaking changes in the `MongoDB.Driver` make sense to release next version as 10.x.x
2. not sure about full support of 9.x.x later (you probably want to use the newest version and I'd encourage to do so), but that won't be a problem to release small fixes/security patches in the future.

**Comment by oriolaakeem** [comment]
@vova3211 any timeline on when this update will be published?

**Comment by vova3211** [comment]
hey hey!

release [9.1.0](https://www.nuget.org/packages/AspNetCore.Identity.Mongo/9.1.0) is ready. Please check it out
