### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by hakeemoriola** [matteofabbri/AspNetCore.Identity.Mongo#44]
Can you still maintain support for IdentityRole<string> and IdentityUser<string> in the MongoRole and MongoUser as this update broke my project.

**Comment by vova3211** [comment]
Hi @hakeemoriola , started from version 6.7.0 `MongoRole` and `MongoUser` use ObjectId type instead of string. It's necessary to increase db productivity (you can google advantages of using ObjectId vs string).

So you need to update your "Users" and "Roles" collections to use _id like ObjectId. Or use versions lower than 6.7.0 if you want keep it like string.

**Comment by hakeemoriola** [comment]
"The property 'Id' of type 'OENT.Entities.ApplicationUser' cannot use element name '_id' because it is already being used by property 'Id' of type 'Microsoft.AspNetCore.Identity.IdentityUser`1[[MongoDB.Bson.ObjectId, MongoDB.Bson, Version=2.10.3.0, Culture=neutral, PublicKeyToken=null]]'."

**Comment by vova3211** [comment]
Can you provide implementation of `OENT.Entities.ApplicationUser`?

**Comment by hakeemoriola** [comment]
[BsonIgnoreExtraElements]
    public class ApplicationUser : MongoUser, IEntityBase<string>
    {
        public bool Admin { get; set; }
        public string Application { get; set; }
        public string City { get; set; }
        public string CompanyId { get; set; }
        public string EnrolleeId { get; set; }
        public virtual Company Company { get; set; }
        public string Country { get; set;}
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
        public string CreatedBy { get; set; }
     
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; } = ObjectId.GenerateNewId().ToString();
    }

public interface IEntityBase<T>
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        string Id { get; set; }
        string CreateDate { get; set; }
        
        string UpdateDate { get; set; }
        string CreatedBy { get; set; }
        //string _id { get; set; }
    }

**Comment by vova3211** [comment]
`MongoUser` already has property "Id" with type ObjectId.
You can delete lines 
```
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = ObjectId.GenerateNewId().ToString();
```
And just use "Id" property where you needed. If you need string representation simple use `Id.ToString()`

**Comment by hakeemoriola** [comment]
i have IEntityBase<string> interface that has Id of string implemented by all my entities 
<img width="1311" alt="Screenshot 2020-04-12 at 15 39 01" src="https://user-images.githubusercontent.com/9089648/79071470-cc8da500-7cd3-11ea-9d05-cfbcfff0bbe7.png">

**Comment by vova3211** [comment]
As i said previously since version 6.7.0 you cann't use Id like string.
You should update your code to use Id like ObjectId or use lower versions of lib.

You can update your interface to handle Id like ObjectId, but it will broke a lot of your code. The easier solution is to create another interface to handle this specific classes (user and role)

**Comment by hakeemoriola** [comment]
Thanks for your help and feedback
