### ISSUE TITLE
ConfirmEmail returns false

### ISSUE THREAD

**Issue by chris40042** [matteofabbri/AspNetCore.Identity.Mongo#68]
Hi, 

First of all, thanks for your project, it helps a lot. But i'm facing an issue, whenever i try to confirm email with token gave in the email, it happens to return "false" but the token seems to be the good one. Result in the below code returns me : "InvalidToken" so it's always false and i can't confirm mail.  How to solve it ?

```
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToAction(nameof(UserController.Index), "User");
            }
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }
            var result = await _userManager.ConfirmEmailAsync(user, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }
```

**Comment by lenwen** [comment]
Hello Chris
This issue has nothing to do whit this project.
I think the issue is encoding of the confirm string. 
When you creating the confirm url. Can you add that code?
This is the code am using.

`
var code = await _userManager.GenerateEmailConfirmationTokenAsync(user).ConfigureAwait(true);
var link2 = Url.Page("/Account/Emailverification", null, new { userId = user.Id, code }, Request.Scheme);
`

You need to use Url.Page to “build” the string. You can search on "url encoding" to learn more.
Or this shod also work if you don’t want to use Url.Page
`code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));`

**Comment by vova3211** [comment]
Yes like said previously @lenwen this issue is not related with this library.

Try to generate token and then immediately validate it. If it's ok, then your token modified outside the app. If no, then it's problem in something else.


Also issue opened a lot time ago - is it still actual?
